### ISSUE TITLE
Remove province selection when clicking on a sea province

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#12]
It is intuitive to click on a sea province in order to deselect a province to close the province view. Nobody cares about sea province information anyways.

**Comment by nickbabcock** [comment]
My preference is to keep all drawer interactions consistent with each other in regards to handling click events.

**Comment by nickbabcock** [comment]
> But what is the point of registering clicks on a sea tile when the sea tile borders aren't even rendered?

You're right. I didn't consider that province borders exclude sea tiles, which does lend weight to this idea.

To understand this viewpoint better, does clicking a sea tile only close the province drawer if it is open? As in, does clicking a sea tile effect any of the other drawers if they happen to be open?

**Comment by crschnick** [comment]
Only the province drawer
