### ISSUE TITLE
How to use VP9 in VideoEncoder

### ISSUE THREAD

**Issue by Vanilagy** [pdx-tools/pdx-tools#154]
Hey,

author of `webm-muxer` here! Saw you using my library so I checked out your project. Seemed like you were having trouble getting VideoEncoder to encode VP9. I've been there too, the problem is that VP9 codec strings are weird and contain a whole bunch of extra settings, whereas VP8 doesn't.

For the codec to be recognized, try using `vp09.00.10.08` in the VideoEncoder. It's what I use and it works like a charm. It's also what I used in my [demo](https://github.com/Vanilagy/webm-muxer/blob/c18d82b5ae108a7521f414e1ffb4d46d14379d0f/demo/script.js#L55).

**Comment by nickbabcock** [comment]
What a welcome surprise! A quick smoke test confirmed that VP9 string works. I must have missed it when looking over the [`VideoEncoder` example](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder/isConfigSupported#examples). Thank you for the tip!

While you are here, do you have any thoughts or tips on VP8 vs VP9 in general? The VP9 webm that is produced is larger (5.16 MB vs 3.4 MB). And both appear to be equally good quality-wise. Maybe it has something to do with the default settings bitrate and framerate, which I'm not setting explicitly:

https://github.com/pdx-tools/pdx-tools/blob/551c95ea3d317eafa75adc446ddacb38c4167d13/src/app/src/features/eu4/features/settings/TimelapseEncoder.tsx#L200-L204

After transcoding to mp4 via ffmpeg.wasm, they come out about the same size, so maybe it's something not to worry about.

PS. Greatly appreciate your library -- a very lightweight library to create webm is much appreciated!

**Comment by Vanilagy** [comment]
I think it would be good practice to explicitly set the bitrate rather than leaving it up to browser defaults. You can even make it be a user setting, although the less the user has to think about, the better. VP9 should be better than VP8 because it's a later codec, but I think it's slightly more resource-intensive. I mean really, we'd want to be using AV1, the newest kid on the block, but that's even more intensive to encode and has less support than VP9.

I'm glad you've found a use in my library! It's a shame you need to convert it again to MP4, given that WebM is quite supported nowadays (except on iOS). Maybe that's a sign I need to start working on `mp4-muxer`... ;)

**Comment by nickbabcock** [comment]
> I think it would be good practice to explicitly set the bitrate rather than leaving it up to browser defaults. You can even make it be a user setting, although the less the user has to think about, the better.

I agree with both points. I think it'll just take some testing to see what formula works best as users can render videos at different resolutions and different level of details. It kinda sorta looks like the default bitrate is 2 MB/s (based on looking at VLC's content bitrate statistic) and is too high as ffmpeg seems to reduce it to 500 KB/s mp4 and it looks quite good.

> It's a shame you need to convert it again to MP4, given that WebM is quite supported nowadays

Don't worry, exporting to mp4 is opt in and the user is sufficiently warned 😄 

![image](https://user-images.githubusercontent.com/2106129/211237478-45461807-8836-4938-aab3-081847cd270f.png)

I forget the original reason I added it, but I think a major player didn't support webm video (was it reddit?)

> Maybe that's a sign I need to start working on `mp4-muxer`... ;)

Ooohhh man, don't get me excited. I'd drop ffmpeg in a heartbeat.
