### ISSUE TITLE
Terrain rendering is disabled by default

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#16]
Terrain rendering makes the map look nicer but it doesn't have a huge performance impact unless you are running on a potato. So I would enable it by default

**Comment by nickbabcock** [comment]
I believe we should focus on making the map rendering more performant as certain devices do take a performance hit and render the map oddly (like a phone or tablet).

![image](https://user-images.githubusercontent.com/2106129/150790381-d07933c6-4edb-4afc-b2e1-187a0b2f79ab.png)

**Comment by nickbabcock** [comment]
I'm going to close this as I'm still happy with the default map behavior
