### ISSUE TITLE
Initialize the savegame view with a good default country filter

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#17]
Right now, the default filter for charts, tables, etc. contains ALL countries, which can't be displayed anyways.
Maybe start off with a good default country filter like neighbours or great powers that contains the countries that are most likely relevant to the user.

**Comment by nickbabcock** [comment]
> Right now, the default filter for charts, tables, etc. contains ALL countries, which can't be displayed anyways.

All countries can be displayed in tables and in a subset of charts (like idea groups).

I'm not opposed to initializing the filter to only players on multiplayer saves, but in general the default country filter is working as designed.

**Comment by nickbabcock** [comment]
Closed by 334244dd62cdbd268500d1bd4de4ff940d8da62b
