### ISSUE TITLE
Logo position is a little bit off

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#19]
![image](https://user-images.githubusercontent.com/72509152/150779846-240567b5-3fc9-4fcc-816d-7ce4ff8ffa54.png)

**Comment by nickbabcock** [comment]
From a design perspective, I believe it is ok that the logo is baseline aligned with the text. Maybe it's something that can be tweaked if logo + text are supposed to be center aligned and not baseline aligned, but I'm honestly not sure 😬
