### ISSUE TITLE
Map not getting rendered on Chrome and Firefox on MacOS with M1 chip

### ISSUE THREAD

**Issue by AleksaC** [pdx-tools/pdx-tools#198]
Chrome gets stuck on the loading animation for some time and after that proceeds to the next page but without the map. This gets logged to the console:
```
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

Firefox on the other hand gets stuck on the loading page forever until it completely crushes if you try doing something.

While the browser is stuck I see `MTLCompilerService` using about a full CPU core for an extended period of time.

To my surprise it works on Safari (usually it's the other way around).

The logs between Safari and the other browser are identical except the other two never get to log `"[  328ms]" – "first render"`

Not sure if this is specific to those browsers on MacOS on apple silicone or MacOS in general.

**Comment by crschnick** [comment]
Can you somehow verify that hardware acceleration is enabled and used in firefox and chrome? WebGL support on macOS has always been a mess, Safari only recently started supporting it completely.

**Comment by AleksaC** [comment]
It's enabled in settings, not sure how to test if it's actually being used

**Comment by crschnick** [comment]
How does the output of https://webglreport.com/?v=2 look like for you?

**Comment by AleksaC** [comment]
![Screenshot 2023-07-16 at 21 27 28](https://github.com/pdx-tools/pdx-tools/assets/25728391/6b8e36bd-72a9-4067-af07-7145ec972ac0)

**Comment by crschnick** [comment]
That looks alright. I would honestly put that down to macOS implementations being weird, as it is not really surprising that it doesn't work there. When we first released the webgl map, no browser on macOS supported it.

There isn't a lot that I can do here to debug this as it is notoriously difficult to do with webgl.

**Comment by crschnick** [comment]
You can try out other resource intensive webgl websites if you can find some and see if they work for you

**Comment by AleksaC** [comment]
I remember playing [counter strike](https://game.play-cs.com/) in browser, still works. I'm guessing that would be somewhat intesive.

**Comment by crschnick** [comment]
That might have been webgl1 though.

Ok so I can confirm that this also happens on my end.
What we do for now is show a note in the event of the webgl context being lost, there isn't a lot more than we can do.

**Comment by nickbabcock** [comment]
Close this as the warning in pdx.tools should cover this. Let me know if I'm missing something.
