### ISSUE TITLE
Leaderboard is called Home

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#20]
![image](https://user-images.githubusercontent.com/72509152/150780042-6885263b-fb28-437a-b302-88636bbf571e.png)

**Comment by nickbabcock** [comment]
As of right now, I think this is ok. The main page prior to the new version was `/eu4`, otherwise I would consider removing this page. It's a list of newest saves, not a leaderboard. If you want to talk about how the home page of a game can be better designed then I'm open for suggestions.

**Comment by crschnick** [comment]
If it is just a list of newest saves, why not call that page "Savegames"

**Comment by nickbabcock** [comment]
As it can be more than a list of save games. If a better design for a game's home page can be implemented then it is reasonable for this list to be moved under `/eu4/saves` (which I believe is currently unused) -- just like how referencing an individual save is `/eu4/saves/<id>`
