### ISSUE TITLE
Map standalone not working

### ISSUE THREAD

**Issue by CaptainJackas** [pdx-tools/pdx-tools#200]
Hi! I noticed in the map folder that the map itself can be built and used separately from the website. When trying to do this I get no errors from npm and the server is launched just fine however the map is not displayed and the following error is displayed in the browser console: 

`Uncaught (in promise) DOMException: The source image could not be decoded. (index.ts:513)`

Am I missing something here? 

I'm not using the dev container btw.

**Comment by nickbabcock** [comment]
I believe the readme is missing important instructions:

- Install [git lfs](https://git-lfs.com/)
- Checkout map images with `git lfs checkout`

If these instructions work, I'll add them to the readme.

**Comment by CaptainJackas** [comment]
Now you mention it, I checked and there was something wrong with my repo -.- I cloned the entire repo again and it is working now! 

Another question came to me when browsing the files looking for something I was missing: how does the map know how to draw the borders? Is there just a static source file for this and if yes where can I find that?

**Comment by nickbabcock** [comment]
You can read up on the [implementation here](https://nickb.dev/blog/simulating-the-eu4-map-in-the-browser-with-webgl/#implementation), but the TLDR: we take provinces.bmp, fill each province with the desired color for the map mode. Map mode borders are calculated dynamically from this process with edge detection. Province edge detection is a bit easier as you can basically do it by just looking at provinces.bmp and neighboring pixels. Country mode borders may be the hardest that requires feeding in a array of each province owner's color.

**Comment by CaptainJackas** [comment]
Awesome, many thanks!
