### ISSUE TITLE
EU4 Crashes After Loading Melted Save w/ RNW

### ISSUE THREAD

**Issue by PfisterFactor** [pdx-tools/pdx-tools#206]
EU4 crashes when playing on the melted save maybe around a month after the game is unpaused. The save has RNW enabled. It crashes around the end of the month.

Saves (both melted and unmelted): 
[saves_that_are_crashing.zip](https://github.com/pdx-tools/pdx-tools/files/12691094/saves_that_are_crashing.zip)

Crash Report:
[eu4_20230921_144057.zip](https://github.com/pdx-tools/pdx-tools/files/12691165/eu4_20230921_144057.zip)

Steps to Reproduce:
- Download the save
- Go to PDX Tools and melt it
- Load into the save (the map is blank as well when loading)
- Unpause and wait until it crashes

Mods Enabled (when save was started - it still crashes with all mods disabled):
- Cmushi's Simpler Terms Mod [Updated]
- Graphical Map Improvements
- Bigger UI V1.35.0
- Uncovered Acceptance Indicator
- Cantons for Colonial Flags
- Random New World Improvements [Updated]
- More RNW Tiles [Updated]
- no province flags

Mod Launcher Playset:
```json
{"game":"eu4","name":"Initial playset","mods":[{"displayName":"Simple Fog of War","enabled":false,"position":0,"steamId":"399253429"},{"displayName":"Stellaris UI Font","enabled":false,"position":1,"steamId":"704256650"},{"displayName":"Bigger UI V1.35.0","enabled":true,"position":2,"steamId":"788906833"},{"displayName":"Uncovered Acceptance Indicator","enabled":true,"position":3,"steamId":"1542140964"},{"displayName":"Cmushi's Simpler Terms Mod [Updated]","enabled":true,"position":4,"steamId":"1999969598"},{"displayName":"The Great Exhibition","enabled":false,"position":5,"steamId":"2016264376"},{"displayName":"Cantons for Colonial Flags","enabled":true,"position":6,"steamId":"2038992950"},{"displayName":"Random New World Improvements [Updated]","enabled":true,"position":7,"steamId":"2786231870"},{"displayName":"More RNW Tiles [Updated]","enabled":true,"position":8,"steamId":"2517126510"},{"displayName":"Graphical Map Improvements","enabled":true,"position":9,"steamId":"253263609"},{"displayName":"no province flags","enabled":true,"position":10,"steamId":"2861738197"}]}
```

**Comment by nickbabcock** [comment]
Ah, random new world saves are not supported

**Comment by crschnick** [comment]
Maybe it could properly output the fact that it is unsupported instead of silently melting it

**Comment by nickbabcock** [comment]
Closing this as now pdx.tools will warn that melted RNW saves can not be resumed in EU4.
