### ISSUE TITLE
Safari 15.1 loading issues

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#22]
When loading the site on my safari browser in the VM, I get the following errors (Not WebGL related):

![image](https://user-images.githubusercontent.com/72509152/150805991-2d05c0a9-024f-4b8f-b57f-bdcd48c855db.png)

**Comment by nickbabcock** [comment]
You'll want to be testing safari 15 on macOS 11 Big Sur or later: https://caniuse.com/webp

Btw, you'll want to create more descriptive issue titles in the future.

**Comment by crschnick** [comment]
I used Safari 15.1
