### ISSUE TITLE
MacOS Big Sur Safari 15.2 map issues so far

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#23]
This is how the map looks like for me on Big Sur + Safari 15.2:
![image](https://user-images.githubusercontent.com/72509152/150829241-fd37dfa4-6662-4cf5-8d89-4d60a2adf3c7.png)

Issues for so far:
- Some tooltips are too short
- Weird sea color (Might be safari changing the color, maybe we can disable this somehow)
- When terrain rendering is disabled, the map gets drawn twice on startup (also happens on other browsers now that I checked)

Furthermore, I still get these errors in the console:
![image](https://user-images.githubusercontent.com/72509152/150830350-92983ea8-befa-4d88-a001-2b5b745415b5.png)

**Comment by crschnick** [comment]
When terrain is enabled, the sea texture is not rendered:
![image](https://user-images.githubusercontent.com/72509152/150831557-de27d09c-d806-4ef2-b494-a661f263eade.png)

**Comment by nickbabcock** [comment]
The issues reported may be a different bug, but here is how the site renders on a 15.3 device (which kinda looks to only have security changes from 15.2)

![image](https://user-images.githubusercontent.com/2106129/182143939-a6428547-d688-43a5-8d22-435a2376546e.png)

Pardon the blurriness of screenshot
