### ISSUE TITLE
Help getting started: Victoria 3 local parsing

### ISSUE THREAD

**Issue by JackYoustra** [pdx-tools/pdx-tools#230]
Hello! I had an idea for some cool views in the victoria 3 save parsing page, so I followed the instructions and I have a copy of the site running on a vscode dev container (VERY slick by the way, works wonderfully, thanks for including.)

I am stuck, however, when actually parsing a file. On the site, my binary victoria 3 save yields a nice graph, but on the local copy, it yields "unable to deserialize due to: deserialize error: missing field `meta_data`". I can't tell, is this because I don't have the ironman key? How would I know / what part of the codebase should I familiarize myself with to understand where this happens?

**Comment by crschnick** [comment]
The ironman keys are not shipped in the repo because Paradox does not like the keys being public. Therefore, they are only included in the production website and not public.

If you want to use a certain save locally, you can use the pdx.tools website to melt it first. Then it should work on your end.

**Comment by crschnick** [comment]
Maybe we can improve the error message when no ironman tokens are included at all vs when they are included but a certain one is missing.

**Comment by nickbabcock** [comment]
Welcome onboard @JackYoustra ! Excited to hear your ideas. I know @kren1 would be happy to lend an ear to your ideas as they've been kickstarting vic3 support in the last couple months. Discussions happen on [discord](https://discord.gg/rCpNWQW) or here. I'm not a Vic3 expert, but I can help with any web frontend work and rust.

As for this issue, yeah let me improve the error message as even I run into this scenario occasionally and need to pause to understand what the error actually means.
