### ISSUE TITLE
Map loading is bugged on firefox

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#29]
Right now, when I open the map, it looks like this:

![image](https://user-images.githubusercontent.com/72509152/150946982-1d5d0985-c0e5-4627-b8a1-f90ae4f2ddae.png)

When I click something it looks like this:
![image](https://user-images.githubusercontent.com/72509152/150947064-0ebb819c-358a-4162-8cd1-f20c6d604a27.png)

**Comment by MSpartaHD** [comment]
I managed to encounter this once on Chrome 97.0.4692.99 (64-bit), however, was not able to reproduce getting it.

**Comment by crschnick** [comment]
How long does it take for the fix to be applied?

**Comment by nickbabcock** [comment]
I typically like to wait to push changes live after pull requests to get merged (it's a todo on my list to have this happen automatically). Changed scripts are cache busted, so there should be no need to disable the cache (and scripts that did not change should be cache).
