### ISSUE TITLE
Map is still rendered twice initially

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#38]
For a split second, I can see an empty terrain map when loading the map with Edge. This only happens when terrain rendering is enabled.

**Comment by nickbabcock** [comment]
I've not yet been able to reproduce this yet with edge + terrain overlay, but I'll keep an eye out for this.

**Comment by crschnick** [comment]
This is how it looks like a split second for me on Edge:
![image](https://user-images.githubusercontent.com/72509152/151117224-be6e4355-4c4f-450e-a333-ab05f08f4c12.png)

Right afterwards, it switches to this:
![image](https://user-images.githubusercontent.com/72509152/151117307-1802d82b-26c1-48ab-94c6-6140506be8fc.png)

**Comment by crschnick** [comment]
Now I also get the same behavior on firefox
