### ISSUE TITLE
Main page drop location has a lot of text

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#42]
I don't think the second sentence is needed here:
![image](https://user-images.githubusercontent.com/72509152/151046033-3803d2d5-8032-46c3-a25a-9a4d54b80d2e.png)

**Comment by nickbabcock** [comment]
Yup, I'm happy to trim down the text, but I'd like to keep the size of the box large so that the click target remains large. Are you suggesting to remove the text and fill the void with additional padding?

**Comment by crschnick** [comment]
yes
