### ISSUE TITLE
Warn user if map is not supported

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#53]
In case the map is not supported (for whatever reason), we can show this information to the user on the front page already. We can check basic webgl requirements on the landing page, that doesn't require any resources.

**Comment by crschnick** [comment]
This could also included to check whether webgl2 is even supported

**Comment by nickbabcock** [comment]
webgl2 check already exists

https://github.com/pdx-tools/pdx-tools/blob/49d0bdf6a23a5ae304e940595b93fb44c93ee176/src/app/src/components/landing/BrowserCheck.tsx#L12-L14

**Comment by crschnick** [comment]
Add the context option `failIfMajorPerformanceCaveat ` to this as well

**Comment by nickbabcock** [comment]
Done in af4cdbe70c079b92ad93c746130c9f562e19d71e

**Comment by crschnick** [comment]
We should also check if the amount of supported texture units in the fragment shader is >= 16
