### ISSUE TITLE
Flickering on map resize

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#55]
When resizing the window, the map flickers and the background is visible for short periods. Maybe we should make the background black or use the map sea color as the background.

**Comment by nickbabcock** [comment]
I've been unsuccessful reproducing, so feel free to expound upon this issue.

**Comment by crschnick** [comment]
When resizing, the canvas is not visible for a short period, which causes the loading icon to show again:

![image](https://user-images.githubusercontent.com/72509152/151694667-9ce06780-5f4d-49ae-8f63-cf14730cf4b9.png)
(Captured while resizing)
