### ISSUE TITLE
Add Social preview image for repo

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#58]

**Comment by nickbabcock** [comment]
Before acting on anything, I'd like for one to showcase the landscape for what other open source sites do for their github social image especially in relation their site's social image.

**Comment by nickbabcock** [comment]
Updated to be in the style of bitwarden:

![image](https://user-images.githubusercontent.com/2106129/153687901-138cae76-934f-445d-9572-beabd0a144c7.png)
![social](https://user-images.githubusercontent.com/2106129/153687928-85612da5-de43-4585-9f5c-94629f5ebce3.png)
