### ISSUE TITLE
Safari 15 Wegbl 2 Metal Failure

### ISSUE THREAD

**Issue by nickbabcock** [pdx-tools/pdx-tools#6]
Safari 15 gained support for webgl2, however Safari 15 users are receiving the following error:

> Link failed: Internal error compiling shader with Metal backend. Please submit this shader, or website as a bug to https://bugs.webkit.org

I believe this is the only thing stopping Safari compatibility, which would be a nice to have.

Maybe a future contributor who has an iOS device could troubleshoot this or report the bug to webkit 😄 

[The standalone map directory, which contains the webgl shaders for reference](https://github.com/pdx-tools/pdx-tools/tree/master/src/map)

**Comment by crschnick** [comment]
The shaders compile and llink on 15.1 for me:

![image](https://user-images.githubusercontent.com/72509152/150807695-e0c206aa-cf24-4629-8db8-c53a3a71b7ff.png)
