### ISSUE TITLE
Move sample and browser info upwards

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#67]
Can we move this part:
![image](https://user-images.githubusercontent.com/72509152/152611772-94d5fdaa-49f3-44de-8a33-eadb1fe94e3c.png)
up such that it is located directly below the drop area.

I don't see why it should be located under the image

**Comment by nickbabcock** [comment]
This is more of a design question. The current design emphasizes the call to action for regular users to analyze a file, while describing the app succinctly. Followed by a screenshot showing what the app is. New users will continue to scroll and find the requirements and the sample. Putting them above the fold seems odd as they are to be easily discovered but are unimportant for returning users. I'm happy to move it, but I'd like to see more thorough reasoning, ideally using examples from other apps communicating the same info, as to why it should be placed above the fold.

**Comment by crschnick** [comment]
If I were a new user, I would like to know how it actually looks and feels like first before searching my computer for the savegames directory. Most new users probably don't have a specific file at hand they can and want to analyze.

If you don't want to move it upwards, maybe highlight this part more with a different background color and give it more space?
Otherwise it is overshadowed by the big image:
![image](https://user-images.githubusercontent.com/72509152/152622897-0a60d91a-fbc8-4282-a3a5-481d07961aee.png)

**Comment by nickbabcock** [comment]
New users are the most likely ones to scroll. And yeah if you want the design of the requirements + sample updated, hit me with some mockups.

**Comment by crschnick** [comment]
Make the icons + description bigger, more padding, and make the color alternate to distinguish it like the other points here:
![image](https://user-images.githubusercontent.com/72509152/152624246-2db3fd1b-9577-4b2e-8cde-fbc34097b8df.png)

**Comment by nickbabcock** [comment]
Ah gotcha, thanks

**Comment by nickbabcock** [comment]
Closing this as now the sample button is right next to the analyze box.

The browser compatibility was moved lower into the body, but if the browser is incompatible, it will be displayed at the top of the page
