### ISSUE TITLE
Don't install dev dependencies globally (npm i -g)

### ISSUE THREAD

**Issue by tkasparek** [pdx-tools/pdx-tools#69]
Hi,
I would like to ask whether it would be possible to not install dev dependencies globally as `just setup` fails for me without superuser privileges on Fedora 35.

```
pdx-tools] (master)$ just setup
++ mktemp -d
+ MY_TMP=/tmp/tmp.I305SUyBw3
+ trap 'rm -rf -- "$MY_TMP"' EXIT
+ npm install -g wasm-pack@0.10.1
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/wasm-pack
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wasm-pack'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wasm-pack'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/wasm-pack'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

**Comment by nickbabcock** [comment]
I agree, it would be desirable to avoid installing build dependencies globally. Do you have a solution in mind?

The original impetus for installing these dependencies globally is that I found it analogous to other projects requiring system packages in order to build (ie: I've used python projects that required the `cairo` package to build). The analogy isn't perfect, so I'm happy to change based on feedback! 

Fwiw, some build dependencies aren't npm packages (like hugo, wasm-opt, and flatc), so any solution would need to encompass these. And hugo installation would need to drop the `dpkg` for this to work on fedora.

**Comment by tkasparek** [comment]
It might be just my obsedancy speaking, but I don't like installing node packages, python modules using `pip` globally and I am really trying to get as much of project dependencies installed without root permissions.  

I've had success with following patch to justfile:
```
   set -euxo pipefail
   MY_TMP="$(mktemp -d)"
   trap 'rm -rf -- "$MY_TMP"' EXIT
-    
+
+  npm config set prefix '~/.local/'
+  mkdir -p ~/.local/bin
+
+  if [[ ! ":$PATH:" == *":$HOME/.local/bin/:"* ]]; then
+    echo 'export PATH=~/.local/bin/:$PATH' >> ~/.bashrc
+    export PATH=~/.local/bin/:$PATH
+  fi
+
   npm install -g wasm-pack@0.10.1
   npm install -g @cloudflare/wrangler
```
The downside is that it works just for bash and not for other shells but as the justfile executes bash so I suppose this is not an issue.

The real issue is that https://github.com/gohugoio/hugo does not provide .rpm packaged binaries so I'll need to look into this one further.

**Comment by nickbabcock** [comment]
With devcontainer support added in #70 and subsequent patches, I think it is a decent state to close this issue. Happy to incorporate any further feedback to make contributions easier!
