### ISSUE TITLE
Show supported savegame version range

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#72]

**Comment by nickbabcock** [comment]
Ideas on where best to show it? Like only on error pages or is this something that should be included on the home page?

**Comment by crschnick** [comment]
You can merge it with a more prominent supported browser list

**Comment by nickbabcock** [comment]
So two lists? Supported browser list and supported game and patch list?

**Comment by crschnick** [comment]
yes, but both lists can be shown at the same spot under the label "Compatibility" or something
