### ISSUE TITLE
Website does not interact with browser addons for dark mode

### ISSUE THREAD

**Issue by crschnick** [pdx-tools/pdx-tools#85]
I am using the https://addons.mozilla.org/en-US/firefox/addon/darkreader/ addon in firefox to display many websites in dark mode that don't have one. However, pdx.tools seems to be the only website I know where this addon does not work for whatever reason.

**Comment by MatthewForrester** [comment]
I am using the same add-on with Firefox for Linux 124.0.1 and it _does_ function correctly on PDX Tools. Unless OP can reproduce, it might be safe to to close this bug report.

**Comment by nickbabcock** [comment]
Thanks for checking @MatthewForrester . I was inspired to take a stab at introducing native support for dark mode and I think it came out decent enough (and I'm counting on you to report if there's any issues on release 😉, I'm kidding I'll dogfood it too)

**Comment by crschnick** [comment]
Yeah now it works
